#!/bin/bash

program=mingw64-qmake-qt5
#program=mingw32-qmake-qt5

datapath="."

$program -project "QT += widgets printsupport" "LIBS += -lgsl -lgslcblas -lm" "QMAKE_CFLAGS += -ffloat-store" "QMAKE_CXXFLAGS += -ffloat-store" "DEFINES += VERSION=1.3"
$program
make -j4
make clean

cp *.png release/
cp *.lib release/
cp *.dat release/

cd release

result=1
while [[ "$result" != "0" ]] ; do
   result=0
   for file in `wine efficiency.exe |& sed "s/.*Library.\(.*\.dll\).(.*/\1/" | sed "/err\:/d"` ; do
      if [ ! -e $file ] ; then
         echo "Missing $file"
         find /usr/ ! -readable -prune -o -name $file -print -exec cp {} ./ ';'
         result=1
      fi
   done
done

cd ..
cp -r release Efficiency
rar a Efficiency.rar Efficiency/*

exit 0

