#!/bin/bash

#program=qmake
program=qmake-qt5
#program=mingw64-qmake-qt5

datapath="/usr/local/share/Efficiency"

if [[ "$program" == "mingw64-qmake-qt5" ]]
   then
   datapath="."
fi

$program -project "QT += widgets printsupport" "LIBS += -lgsl -lgslcblas -lm" "QMAKE_CFLAGS += -ffloat-store" "QMAKE_CXXFLAGS += -ffloat-store" "DEFINES += VERSION=1.4 CUSTOM" "INCLUDEPATH += include"
$program
make
make clean

exit 0

